application: ajpaz531
version: test
runtime: python27
api_version: 1
threadsafe: true

libraries:
 - name: jinja2
  version: latest  

handlers:
- url: /rest/.*
  script: ds.app
  login: required

- url: /api/.*
  script: api.app

- url: /(index\.html)?
  static_files: index.html
  upload: index.html

- url: /assets
  static_dir: assets
