application: ajpaz531
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: /(index\.html)?
  static_files: index.html
  upload: index.html

- url: /assets
  static_dir: assets
