application: ajpaz531
version: test
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6 

handlers:

- url: /rest/.*
  script: src.main.python.ds.app
  login: required

- url: /api/.*
  script: src.main.python.api.app

- url: /(index\.html)?
  static_files: index.html
  upload: index.html
  login: required

- url: /assets
  static_dir: assets

- url: /bower_components
  static_dir: bower_components
